name: bon_state
description: "A state management library that embraces simplicity and explicitness."
version: 0.0.1
repository: https://github.com/Yoeri-z/bon_state
issue_tracker: https://github.com/Yoeri-z/bon_state/issues
topics:
  - state-management
  - dependency-injection
  - reactivity

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
